### PR TITLE
Added a link for React fetch

### PR DESCRIPTION
**Pull request by buketkonuk**
How to fetch data in React

### CODE REVIEW

**Review by GrahamHewett — CHANGES_REQUESTED** [review]
Please check your typos! href not hreft prop please on line 81

**Review by GrahamHewett — CHANGES_REQUESTED** [review]
Please remove your package.lock.json from the commit by adding it to the .gitIgnore file

**Comment by buketkonuk** [comment]
added package-lock.json to gitIgnore

**Review by GrahamHewett — APPROVED** [review]
Thanks for the suggestion.
I deleted the package-lock.json file from your pull request and have now approved it.
Feel free to open another pull request anytime to practice the process before you start your team app.

**Pull request merged**
